//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationMatch.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzureCourse_LocationMatchEntities : DbContext
    {
        public AzureCourse_LocationMatchEntities()
            : base("name=AzureCourse_LocationMatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Location> Locations { get; set; }
        public DbSet<LocationList> LocationLists { get; set; }
        public DbSet<Track> Tracks { get; set; }
        public DbSet<LocationMatchAnalysi> LocationMatchAnalysis { get; set; }
    }
}
